scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ['localhost:9090'] 
        labels:
          grupo: 'Prometheus' 

  - job_name: ApiProduto 
    static_configs:
      - targets: ['13.89.109.26']
        labels:
          grupo: 'AspNetCore'

# kubectl create configmap file-configmap --from-file=prometheus.yaml