apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-deployment
  namespace: pedelogo-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: amisaka/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          name: http 
        - containerPort: 443 
          name: https 
        imagePullPolicy: Always 
        envFrom:
          - name: api-configmap
        env: 
        - name: Mongo__User 
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: mongodb-secret
        - name: Mongo_Password 
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongodb-secret

# Configuração com ConfigMap
        #     configMapKeyRef:
        #       key: MONGO_INITDB_ROOT_USERNAME
        #       name: mongodb-configmap
        # - name: Mongo_Password 
        #   valueFrom:
        #     configMapKeyRef:
        #       key: MONGO_INITDB_ROOT_PASSWORD
        #       name: mongodb-configmap

# Configuração sem ConfigMap
        # env: 
        # - name: Mongo__Host 
        #   value: "mongo-service" 
        # - name: Mongo__User 
        #   value: "mongouser" 
        # - name: Mongo_Password 
        #   value: "mongopwd" 
        # - name: Mongo__Port
        #   value: "27017" 
        # - name: Mongo__DataBase 
        #   value: "admin" 
